// data.js - 纯剧本数据文件
const scriptData = [
    { speaker: "???", text: "怎么这么黑", image: "img/empty.jpg",autoNext: 1500},
    { speaker: "???", text: "应该是这么走?",autoNext: 3000},
    { speaker: "???", text: "。。。。。。",autoNext: 6000},
    { speaker: "???", text: "啊。", video: "img/smile-disappear.mp4", autoNext: 2000 },
    { speaker: "???", text: "你好啊~nzy同学", autoNext: 1500 },
    { speaker: "???", text: "生日快乐！", autoNext: 3500 },
    { speaker: "???", text: "不对，", image: "img/empty.jpg", autoNext: 1500},
    { speaker: "???", text: "是nzy本人吧？"},
    { speaker: "???", text: "不赖，", video: "img/appear.mp4", autoNext: 3200},
    { speaker: "???", text: "生日快乐！", video: "img/talk.mp4"},
    { speaker: "???", text: "都不好奇我是谁吗？"},
    { speaker: "???", text: "~既然你诚心诚意的问了，那我就大发慈悲的回答你（", autoNext: 1500 },
    { speaker: "???", text: "我就是salmon", autoNext: 1500 },
    { speaker: "salmon", text: "嗯姑且可以把我理解为lsm半个自设", autoNext: 1500 },
    { speaker: "salmon", text: "你应该知道，她要英语考试暂时没空搭理你", autoNext: 1500 },
    { speaker: "salmon", text: "所以派我先来给你过生日", autoNext: 1500 },
    { speaker: "salmon", text: "是不是很开心~", image: "img/smile.jpg"},
    { speaker: "salmon", text: "过生日的第一步！", autoNext: 1500 },
    { speaker: "salmon", text: "送礼物！", autoNext: 2000 },
    { speaker: "salmon", text: "我记得她给了我一大堆东西。。。", autoNext: 1500 },
    { speaker: "salmon", text: "我找找。。。", image: "img/empty.jpg"},
    { speaker: "salmon", text: "别催！", autoNext: 6000 },
    { speaker: "salmon", text: "有了！", autoNext: 1500 ,effect: "shake",},
    { speaker: "salmon", text: "啊！",video: "img/before fall.mp4", effect: "shake", autoNext: 2800 },
    { speaker: "salmon", text: "好痛QAQ！",image: "img/dark.jpg"},
    { speaker: "salmon", text: "。。。", autoNext: 4000 },
    { speaker: "salmon", text: "nzy同学的礼物！",image: "img/fall.jpg"},
    { speaker: "salmon", text: "可以解决！可以解决的！", video: "img/appear.mp4", autoNext: 1000},
    { speaker: "salmon", text: "求你了能不能不要告诉lsm她会杀了我的QAQ", image: "img/cry.jpg", autoNext: 1500},
    { speaker: "salmon", text: "我帮你把礼物找回来！", },
    { speaker: "salmon", text: "lsm和我说：" ,video: "img/talk.mp4",autoNext: 1500},
    { speaker: "salmon", text: "每一份礼物都经过了她的精心思考和精妙设计",autoNext: 1000},
    { speaker: "salmon", text: "而且礼物最多只会落回学校里了不会更远了！" , autoNext: 1000},
    { speaker: "salmon", text: "就在希望礼物被用到的地方！" ,},
    { speaker: "salmon", text: "啊啊啊啊啊啊啊我知道范围大了点" , autoNext: 1000,effect: "shake",},
    { speaker: "salmon", text: "等下", image: "img/empty.jpg", autoNext: 2000},
    { speaker: "salmon", text: "这里有三份lsm准备礼物时的思维碎片！你看看！一定能找到线索！",video: "img/talk.mp4"},
    { speaker: "salmon", text: "加油。我相信你。" , image: "img/empty.jpg" ,action: "START_PUZZLE_1"},
    // --- 谜题1结束后的剧情 ---
    { speaker: "Salmon", video: "img/talk.mp4",text: "诶呀诶呀没想到lsm对你评价居然这么高~",autoNext: 1500},
    { speaker: "Salmon", text: "这下知道你的礼物去哪里了吗？",autoNext: 1500},
    { speaker: "作者", image: "img/dark.jpg",text: "拿到礼物之后再继续"},
    { speaker: "Salmon", video: "img/talk.mp4",text: "等一下真的会有人想在学创看哲学书吗。。。",autoNext: 1500},
    { speaker: "Salmon（小声）", image: "img/dark.jpg",text: "陆思萌导演你认真的吗这个剧本会不会有点太牵强了",autoNext: 1500},
    { speaker: "作者", text: "凑合着看得了考试周写的哪有不疯的，哇我能在截至日期前赶出来就谢天谢地了还和我讲逻辑（",autoNext: 1500},
    { speaker: "Salmon", video: "img/talk.mp4",text: "。。。咳咳",autoNext: 2000},
    { speaker: "Salmon", text: "至少知道你的礼物不全是小破烂不是吗~",autoNext: 1500},
    { speaker: "Salmon", text: "。虽然我很确定小破烂应该在其他地方",autoNext: 1500},
    { speaker: "Salmon",text: "小贺卡记得留好",autoNext: 1500},
    { speaker: "Salmon",text: "也许是开启某把锁的钥匙呢~",autoNext: 1500},
    { speaker: "Salmon", text: "好了就说这么多，抓紧时间，准备好开始寻找下一份礼物了吗？" },
    { speaker: "Salmon", text: "出发！", action: "START_PUZZLE_2" },
    // --- 谜题2结束后的剧情 ---
    { speaker: "Salmon", video: "img/talk.mp4",text: "第二份礼物的地点。。。你知道了吗？" },
    { speaker: "Salmon", text: "或许可以在第一份礼物的小破烂里找到线索？" },
    { speaker: "Salmon",text: "毕竟破烂之间应该是相通的吧kkk",autoNext: 1500},
    { speaker: "作者", image: "img/dark.jpg",text: "拿到礼物之后再继续"},
    { speaker: "Salmon", video: "img/talk.mp4",text: "哇~~~~~小破烂大礼包来了",autoNext: 1500},
    { speaker: "Salmon",text: "恭喜你找到了所有礼物！",autoNext: 1500},
    { speaker: "Salmon",text: "股掌！"},
    { speaker: "Salmon",text: "不过来都来了还有一段思维碎片也一起听了吧"},
    { speaker: "Salmon", text: "让lsm尴尬的事情我一向很乐意做", action: "START_PUZZLE_3" },
    //谜题三
    { speaker: "Salmon", video: "img/talk.mp4",text: "那么，过生日的第二个环节",autoNext: 1500},
    { speaker: "Salmon", video: "img/talk.mp4",text: "许个愿吧"},
    { speaker: "作者", image: "img/start.gif",text: "点击屏幕吹灭蜡烛"},
    { speaker: "作者", video: "img/blow_candle.mp4",text: "生日快乐",autoNext: 2000},
    { speaker: "Salmon", video: "img/talk.mp4",text: "最后一个环节",autoNext: 1500},
    { speaker: "Salmon", text: "吃蛋糕",autoNext: 1500},
    { speaker: "Salmon", text: "什么？赛博蛋糕不能吃？",autoNext: 1500},
    { speaker: "Salmon", text: "你怎么就那么确定",autoNext: 1500},
    { speaker: "Salmon（笑）", text: "虚构的赛博蛋糕就一定不能成真呢",autoNext: 1500},
    { speaker: "Salmon", text: "lsm送给你的荧光笔也许是时候发挥它的用处了不是吗~",autoNext: 1500},
    { speaker: "Salmon", text: "去寻找虚拟照进现实的窗口",autoNext: 1500},
    { speaker: "作者", image: "img/dark.jpg",text: "找到“蛋糕”之后再继续"},
    { speaker: "Salmon", text: "生日快乐",autoNext: 1500},
    { speaker: "Salmon", text: "请尽情享用你的蛋糕吧",autoNext: 1500},
    { speaker: "Salmon", text: "哦对了应该还有一封信",autoNext: 1500},
    { speaker: "Salmon", text: "本来lsm让我念给你听的来着",autoNext: 1500},
    { speaker: "Salmon", text: "实在是太恶心了我尴尬癌犯了真是抱歉啊",autoNext: 1500},
    { speaker: "Salmon", text: "我和蛋糕一起传过去了你自己看吧。。。",autoNext: 1500},
    { speaker: "Salmon", text: "看了那么多思维碎片之后，这封信所写的，对你来说也许还是太收敛了（",autoNext: 1500},
    { speaker: "Salmon", text: "希望lsm永远也不会知道今天生日的意外",autoNext: 1500},
    { speaker: "Salmon（笑）", text: "但也未必是件坏事不是吗",autoNext: 1500},
    { speaker: "Salmon", text: "有些话如果不是借这样的机会可能永远都不会说出口",autoNext: 1500},
    { speaker: "Salmon", text: "不过我觉得，还是应该给你最真诚，最真实的生日祝福",autoNext: 1500},
    { speaker: "Salmon", text: "不如猜猜今天发生的到底是意外，还是我的有意而为~",autoNext: 1500},
    { speaker: "Salmon", text: "再一次，生日快乐",autoNext: 1500},
    { speaker: "Salmon",video: "img/talk.mp4",text: "其实也许还会有最后一份礼物",autoNext: 1500},
    { speaker: "Salmon",text: "这取决于你是否愿意把它看作礼物。。。",autoNext: 1500},
    { speaker: "Salmon",text: "一个从英语考场里新鲜出炉的lsm kkk",autoNext: 1500},
    { speaker: "Salmon",text: "我可以帮你打包起来放好",autoNext: 1500},
    { speaker: "Salmon",text: "时间不早了我也该走了",autoNext: 1500},
    { speaker: "Salmon",text: "最后的最后，",autoNext: 1500},
    { speaker: "S作al者mon",text: "新的一岁，愿你所愿皆所得，想去的远方，都一步步走到。\n" +
            "\n" +
            "愿你日日是好日，有时而风，时而雨，时而烈酒入喉，时而黄昏温柔。悲喜都尽兴，不枉少年游。\n" +
            "\n" +
            "愿你永葆赤子之心，多年后，若灯下围坐，杯沿碰响，可把酒言欢，笑谈从前。\n" +
            "\n",autoNext: 2000 },
    { speaker: "Salmon",text: "生日快乐，nzy",autoNext: 2500},
    { speaker: "Salmon",text: " ",autoNext: 2500, action: "GAME_END" },
];